<a href="https://colab.research.google.com/github/dehademir/Math-2024-25-Winter/blob/main/4.%20Determinants%20from%20the%20Gauss%20Method%20and%20Triangular%20Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import numpy as np

def row_operations_to_upper_triangular(matrix):
    matrix = matrix.astype(float)
    rows, cols = matrix.shape
    for i in range(min(rows, cols)):
        if matrix[i, i] != 0:
            for j in range(i + 1, rows):
                factor = matrix[j, i] / matrix[i, i]
                matrix[j] -= factor * matrix[i]
    return matrix

A = np.array([[12, 3, -18], [-4, 0, 0]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A_upper = row_operations_to_upper_triangular(A.copy())
B_upper = row_operations_to_upper_triangular(B.copy())

det_A = np.prod(np.diagonal(A_upper))
det_B = np.prod(np.diagonal(B_upper))

print("Upper triangular form of A:")
print(A_upper)
print(f"det(A) = {det_A}")

print("Upper triangular form of B:")
print(B_upper)
print(f"det(B) = {det_B}")


Upper triangular form of A:
[[ 12.   3. -18.]
 [  0.   1.  -6.]]
det(A) = 12.0
Upper triangular form of B:
[[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  0.]]
det(B) = -0.0
