<a href="https://colab.research.google.com/github/dehademir/Math-2024-25-Winter/blob/main/6.%20Inverse%20of%20a%20Matrix%20using%20the%20Gauss%20Method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

augmented_matrix_A = np.hstack([A, np.eye(2)])

rows, cols = augmented_matrix_A.shape

for i in range(rows):
    augmented_matrix_A[i] = augmented_matrix_A[i] / augmented_matrix_A[i, i]
    for j in range(rows):
        if j != i:
            augmented_matrix_A[j] -= augmented_matrix_A[i] * augmented_matrix_A[j, i]

A_inv = augmented_matrix_A[:, 2:]
print(A_inv)



[[-2.   1. ]
 [ 1.5 -0.5]]


In [57]:
B = np.array([[1, 2, 3],
              [4, 5, 1],
              [2, 3, 2]])

augmented_matrix_B = np.hstack([B, np.eye(3)])

rows, cols = augmented_matrix_B.shape

for i in range(rows):
    augmented_matrix_B[i] = augmented_matrix_B[i] / augmented_matrix_B[i, i]
    for j in range(rows):
        if j != i:
            augmented_matrix_B[j] -= augmented_matrix_B[i] * augmented_matrix_B[j, i]

B_inv = augmented_matrix_B[:, 3:]
print(B_inv)


[[  7.   5. -13.]
 [ -6.  -4.  11.]
 [  2.   1.  -3.]]
